# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxd-virtual-machine.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
    ];

  networking.defaultGateway = "10.38.154.1";
  networking.nameservers = [ "1.1.1.1" ];
  networking.enableIPv6 = false;
  networking.firewall.enable = false;
  networking.dhcpcd.enable = false;
  networking.interfaces.eth0.ipv4.addresses = [{
    address = "{{node.name}}";
    prefixLength = 24;
  }];

  services.k3s = {
    enable = true;
    role = "server";
    token = "{{join_token}}";
{% if node.initiator %}
    clusterInit = true;
{% else %}
    serverAddr = "https://{{join_address}}:6443";
{% endif %}
  };

  environment.systemPackages = with pkgs; [
    htop
  ];

  system.stateVersion = "23.11";
}
