# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxd-virtual-machine.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
    ];

  boot.loader.grub.devices = ["{{node.boot_device}}"];
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.KbdInteractiveAuthentication = false;
    settings.PermitRootLogin = "yes";
  };

  networking.hostName = "{{node.name}}";
  networking.defaultGateway = "{{cluster.default_gateway}}";
  networking.nameservers = [ "1.1.1.1" ];
  networking.enableIPv6 = false;
  networking.firewall.enable = false;
  networking.dhcpcd.enable = false;
  networking.interfaces.{{node.interface}}.ipv4.addresses = [{
    address = "{{node.ip}}";
    prefixLength = 24;
  }];

  services.k3s = {
    enable = true;
    role = "server";
    token = "{{cluster.join_token}}";
{% if node.initiator %}
    clusterInit = true;
{% else %}
    serverAddr = "https://{{cluster.join_address}}:6443";
{% endif %}
  };

  environment.systemPackages = with pkgs; [
    htop
  ];

  nix.optimise.automatic = true;
  nix.gc.automatic = true;
  boot.tmp.cleanOnBoot = true;
  boot.kernelModules = [ "rbd" ];
}
